//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.36373
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServiceHealthCheck
{

    /// <summary>
    /// The class for initialization of Windows form.
    /// </summary>
    public partial class ServiceCenter
    {
        #region Private fields

        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Browse Button
        /// </summary>
        private System.Windows.Forms.Button browse;

        /// <summary>
        /// Data Grid of Services.
        /// </summary>
        private System.Windows.Forms.DataGridView dataGridView1;

        /// <summary>
        /// Label of Application
        /// </summary>
        private System.Windows.Forms.Label label1;

        /// <summary>
        /// Stop Button
        /// </summary>
        private System.Windows.Forms.Button stop;

        /// <summary>
        /// IIS reset Button
        /// </summary>
        private System.Windows.Forms.Button restartAll;

        /// <summary>
        /// Start Button
        /// </summary>
        private System.Windows.Forms.Button start;

        /// <summary>
        /// IIS Stop Button
        /// </summary>
        private System.Windows.Forms.Button stopAll;

        /// <summary>
        /// Tool Tip Info
        /// </summary>
        private System.Windows.Forms.ToolTip toolTipInfo;

        /// <summary>
        /// Clear Selection Button
        /// </summary>
        private System.Windows.Forms.Button clearSelection;

        /// <summary>
        /// Refresh Status
        /// </summary>
        private System.Windows.Forms.Button Refresh;

        #endregion

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (this.components != null))
            {
                this.components.Dispose();
            }

            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(ServiceCenter));
            this.browse = new System.Windows.Forms.Button();
            this.dataGridView1 = new System.Windows.Forms.DataGridView();
            this.label1 = new System.Windows.Forms.Label();
            this.restartAll = new System.Windows.Forms.Button();
            this.stopAll = new System.Windows.Forms.Button();
            this.toolTipInfo = new System.Windows.Forms.ToolTip(this.components);
            this.Refresh = new System.Windows.Forms.Button();
            this.clearSelection = new System.Windows.Forms.Button();
            this.start = new System.Windows.Forms.Button();
            this.stop = new System.Windows.Forms.Button();
            this.Explore = new System.Windows.Forms.Button();
            ((System.ComponentModel.ISupportInitialize)(this.dataGridView1)).BeginInit();
            this.SuspendLayout();
            // 
            // browse
            // 
            this.browse.Location = new System.Drawing.Point(729, 79);
            this.browse.Name = "browse";
            this.browse.Size = new System.Drawing.Size(97, 23);
            this.browse.TabIndex = 1;
            this.browse.Text = "Browse";
            this.browse.UseVisualStyleBackColor = true;
            this.browse.Click += new System.EventHandler(this.Browse_Click);
            // 
            // dataGridView1
            // 
            this.dataGridView1.AllowUserToAddRows = false;
            this.dataGridView1.AllowUserToDeleteRows = false;
            this.dataGridView1.AllowUserToOrderColumns = true;
            this.dataGridView1.AllowUserToResizeColumns = false;
            this.dataGridView1.AllowUserToResizeRows = false;
            this.dataGridView1.Location = new System.Drawing.Point(30, 79);
            this.dataGridView1.Name = "dataGridView1";
            this.dataGridView1.RowHeadersWidth = 70;
            this.dataGridView1.Size = new System.Drawing.Size(666, 455);
            this.dataGridView1.TabIndex = 2;
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.Font = new System.Drawing.Font("Arial Black", 15F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label1.ForeColor = System.Drawing.SystemColors.Highlight;
            this.label1.Location = new System.Drawing.Point(30, 26);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(300, 28);
            this.label1.TabIndex = 7;
            this.label1.Text = "Web Service Health Check";
            // 
            // restartAll
            // 
            this.restartAll.Location = new System.Drawing.Point(729, 167);
            this.restartAll.Name = "restartAll";
            this.restartAll.Size = new System.Drawing.Size(97, 23);
            this.restartAll.TabIndex = 10;
            this.restartAll.Text = "IIS_Reset";
            this.restartAll.UseVisualStyleBackColor = true;
            this.restartAll.Click += new System.EventHandler(this.Restart_Click);
            // 
            // stopAll
            // 
            this.stopAll.Location = new System.Drawing.Point(729, 138);
            this.stopAll.Name = "stopAll";
            this.stopAll.Size = new System.Drawing.Size(97, 23);
            this.stopAll.TabIndex = 11;
            this.stopAll.Text = "IIS_Stop";
            this.stopAll.UseVisualStyleBackColor = true;
            this.stopAll.Click += new System.EventHandler(this.IIS_Stop_Click);
            // 
            // toolTipInfo
            // 
            this.toolTipInfo.AutomaticDelay = 1000;
            this.toolTipInfo.ShowAlways = true;
            this.toolTipInfo.ToolTipTitle = "Info";
            // 
            // Refresh
            // 
            this.Refresh.Image = global::WebServiceHealthCheck.Properties.Resources.RefreshDashboard;
            this.Refresh.Location = new System.Drawing.Point(766, 108);
            this.Refresh.Name = "Refresh";
            this.Refresh.Size = new System.Drawing.Size(24, 24);
            this.Refresh.TabIndex = 13;
            this.toolTipInfo.SetToolTip(this.Refresh, "Refresh Sites");
            this.Refresh.UseVisualStyleBackColor = true;
            this.Refresh.Click += new System.EventHandler(this.Refresh_Click);
            // 
            // clearSelection
            // 
            this.clearSelection.Location = new System.Drawing.Point(729, 196);
            this.clearSelection.Name = "clearSelection";
            this.clearSelection.Size = new System.Drawing.Size(97, 23);
            this.clearSelection.TabIndex = 12;
            this.clearSelection.Text = "Clear Selection";
            this.clearSelection.UseVisualStyleBackColor = true;
            this.clearSelection.Click += new System.EventHandler(this.ClearSelection_Click);
            // 
            // start
            // 
            this.start.Image = ((System.Drawing.Image)(resources.GetObject("start.Image")));
            this.start.Location = new System.Drawing.Point(729, 108);
            this.start.Name = "start";
            this.start.Size = new System.Drawing.Size(24, 24);
            this.start.TabIndex = 9;
            this.start.UseVisualStyleBackColor = true;
            this.start.Click += new System.EventHandler(this.Start_Click);
            // 
            // stop
            // 
            this.stop.Image = ((System.Drawing.Image)(resources.GetObject("stop.Image")));
            this.stop.Location = new System.Drawing.Point(802, 108);
            this.stop.Name = "stop";
            this.stop.Size = new System.Drawing.Size(24, 24);
            this.stop.TabIndex = 8;
            this.stop.UseVisualStyleBackColor = true;
            this.stop.Click += new System.EventHandler(this.Stop_Click);
            // 
            // Explore
            // 
            this.Explore.Location = new System.Drawing.Point(729, 225);
            this.Explore.Name = "Explore";
            this.Explore.Size = new System.Drawing.Size(97, 23);
            this.Explore.TabIndex = 14;
            this.Explore.Text = "Explore";
            this.Explore.UseVisualStyleBackColor = true;
            this.Explore.Click += new System.EventHandler(this.Explore_Click);
            // 
            // ServiceCenter
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(867, 581);
            this.Controls.Add(this.Explore);
            this.Controls.Add(this.Refresh);
            this.Controls.Add(this.clearSelection);
            this.Controls.Add(this.stopAll);
            this.Controls.Add(this.restartAll);
            this.Controls.Add(this.start);
            this.Controls.Add(this.stop);
            this.Controls.Add(this.label1);
            this.Controls.Add(this.browse);
            this.Controls.Add(this.dataGridView1);
            this.MaximizeBox = false;
            this.Name = "ServiceCenter";
            this.Text = "ServiceCenter";
            this.Load += new System.EventHandler(this.ServiceCenter_Load);
            ((System.ComponentModel.ISupportInitialize)(this.dataGridView1)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion        

        private System.Windows.Forms.Button Explore;

        
    }
}